################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
Utility \
Scenes/WarScene \
Scenes/WarScene/AESOPActions \
Scenes/TenisScene \
Scenes \
Scenes/PingPongScene \
Scenes/PhysXScene \
Scenes/NetworkScene \
Scenes/NetworkScene/Network \
Scenes/MainScene \
Scenes/FlashScene \
Scenes/CubeScene \
Rendering/RenderPass \
Rendering/PostFX \
Rendering/PostFX/CustomOperators \
Rendering/Lighting \
Rendering/Lighting/ShadowMapping \
Rendering \
Rendering/Camera \
Platform/Video/Textures \
Platform/Video/Shaders \
Platform/Video \
Platform/Video/OpenGL/glsw \
Platform/Video/OpenGL \
Platform/Video/OpenGL/Textures \
Platform/Video/OpenGL/Shaders \
Platform/Video/OpenGL/Buffers \
Platform/Video/OpenGL/Buffers/VertexBuffer \
Platform/Video/OpenGL/Buffers/ShaderBuffer \
Platform/Video/OpenGL/Buffers/PixelBuffer \
Platform/Video/OpenGL/Buffers/Framebuffer \
Platform/Video/Direct3D \
Platform/Video/Direct3D/Textures \
Platform/Video/Direct3D/Shaders \
Platform/Video/Direct3D/Buffers/VertexBuffer \
Platform/Video/Direct3D/Buffers/ShaderBuffer \
Platform/Video/Direct3D/Buffers/PixelBuffer \
Platform/Video/Direct3D/Buffers/Framebuffer \
Platform/Video/Buffers/ShaderBuffer \
Platform/Video/Buffers/Framebuffer \
Platform/Threading \
Platform/Platform \
Platform/Input \
Platform/Audio/sdl_mixer \
Platform/Audio/openAl \
Platform/Audio \
Physics \
Physics/PhysX \
Physics/PhysX/Actors \
Managers \
Libs/ReCast/RecastContrib/fastlz \
Libs/ReCast/ReCast/Source \
Libs/ReCast/DetourTileCache/Source \
Libs/ReCast/DetourCrowd/Source \
Libs/ReCast/Detour/Source \
Libs/ReCast/DebugUtils/Source \
Libs/GLIM \
Libs/CPPGoap \
Graphs \
Graphs/Components \
Geometry/Shapes \
Geometry/Material \
Geometry/Importer \
Geometry/Animations \
GUI \
GUI/GUIEditor \
GUI/CEGUIAddons \
Environment/Water \
Environment/Vegetation \
Environment/Terrain \
Environment/Terrain/Quadtree \
Environment/Sky \
Dynamics/WeaponSystem/Weapons \
Dynamics/WeaponSystem/Projectile \
Dynamics/WeaponSystem/Ammunition \
Dynamics/Entities/Units \
Dynamics/Entities/Triggers \
Dynamics/Entities/Particles \
Dynamics/Entities/Particles/ConcreteUpdaters \
Dynamics/Entities/Particles/ConcreteGenerators \
Dynamics/Entities \
Core \
Core/Resources \
Core/Resources/ConcreteLoaders \
Core/MemoryManagement \
Core/Math \
Core/Math/BoundingVolumes \
AI/Sensors \
AI/PathFinding/Waypoints \
AI/PathFinding/NavMeshes \
AI/PathFinding/NavMeshes/DetourTileCache \
AI/PathFinding \
AI/ActionInterface \
AI \

